services:
  db:
    image: postgres:15
    container_name: storeguard_db
    environment:
      POSTGRES_USER: storeguard
      POSTGRES_PASSWORD: storeguard
      POSTGRES_DB: storeguard
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U storeguard"]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  dbdata:
